[tool.poetry]
name = "wagtail-org"
version = "2.2.0"
description = "The wagtail.org Wagtail site"
authors = ["Torchbox <hello@torchbox.com>"]
license = "BSD-3-Clause"
readme = "README.md"
packages = [{include = "wagtailio"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"
django = "~5.0.6"
wagtail = "~6.2.2"
psycopg2 = "~2.9"
gunicorn = "~21.2.0"
dj-database-url = "~2.3.0"
django-basic-auth-ip-whitelist = "~0.6"
django-csp = "~3.8"
django-manifest-loader = "~1.0.0"
django-pattern-library = "~1.2.0"
django-permissions-policy = "~4.22"
django-referrer-policy = "~1.0"
django-storages = { version ="~1.13", extras = ["boto3"] }
markdown = "~3.7"
pygments = "~2.18"
requests = "~2.32.3"
scout-apm = "~3.2"
sentry-sdk = "~2.17"
wagtail-font-awesome-svg = "~1.0.1"

wagtailmedia = "~0.15.2"
whitenoise = "~6.7"
django-redis = "~5.4"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
djhtml = "3.0.4"
flake8 = "6.0.0"
flake8-assertive = "2.1.0"
flake8-blind-except = "0.2.1"
flake8-comprehensions = "3.10.1"
isort = "5.12.0"
pre-commit = "2.20.0"
